### ISSUE TITLE
   May I ask the specific meanings of each parameter?

### ISSUE THREAD

**Issue by G-Naughty** [jbwang1997/OBBDetection#34]
dict(type='RandomOBBRotate', rotate_after_flip=True,
         angles=(0, 0), vert_rate=0.5, vert_cls=['roundabout', 'storage-tank']),
   May I ask the specific meanings of each parameter,especially 'vert_cls'

**Comment by jbwang1997** [comment]
- `rotate_after_flip` is a flap indicating the order of `OBBRandomFlip` and `RandomOBBRotate`. It changes the action order in `MultiScaleFlipRotateAug`.
- `angles` is the angle range of `RandomOBBRotate`, `(0, 0)` means no rotation. Because `OBBRandomFlip` can flip images horizontally and vertically, we only set `angles` being `(0, 90)` in experiments.
- `vert_rate` is the probability of the vertical rotation (rotate 0, 90, 180, 270 degrees).
- `vert_cls` is a list containing the classes whose bounding boxes are actually horizontal. If an image has a vert_cls instance, `RandomOBBRotate` will only do vertical rotation.

**Comment by G-Naughty** [comment]
Thank you very much!
